/**
 * Pre-loaded Food Items Database
 * Enhanced with Macronutrients: Carbohydrates (g), Protein (g), Fats (g), and Fiber (g).
 */
export const INITIAL_FOOD_ITEMS = [
  {
    "id": "food-1",
    "name": "Plain Rice",
    "category": "Rice",
    "calories": 205,
    "carbonFootprint": 0.28,
    "carbs": 45,
    "protein": 4.2,
    "fat": 0.4,
    "fiber": 0.6,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-2",
    "name": "Jeera Rice",
    "category": "Rice",
    "calories": 250,
    "carbonFootprint": 0.33,
    "carbs": 48,
    "protein": 4.5,
    "fat": 4.5,
    "fiber": 0.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-3",
    "name": "Veg Pulao",
    "category": "Rice",
    "calories": 320,
    "carbonFootprint": 0.42,
    "carbs": 52,
    "protein": 6.0,
    "fat": 9.5,
    "fiber": 2.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-4",
    "name": "Veg Biryani",
    "category": "Rice",
    "calories": 390,
    "carbonFootprint": 0.55,
    "carbs": 58,
    "protein": 8.0,
    "fat": 13.5,
    "fiber": 3.5,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-5",
    "name": "Chicken Biryani",
    "category": "Rice",
    "calories": 540,
    "carbonFootprint": 1.95,
    "carbs": 55,
    "protein": 28.0,
    "fat": 22.0,
    "fiber": 2.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-6",
    "name": "Mutton Biryani",
    "category": "Rice",
    "calories": 620,
    "carbonFootprint": 5.20,
    "carbs": 54,
    "protein": 32.0,
    "fat": 28.0,
    "fiber": 2.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-7",
    "name": "Dal Tadka",
    "category": "Dal",
    "calories": 220,
    "carbonFootprint": 0.42,
    "carbs": 30,
    "protein": 12.0,
    "fat": 6.5,
    "fiber": 6.5,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-8",
    "name": "Dal Fry",
    "category": "Dal",
    "calories": 240,
    "carbonFootprint": 0.45,
    "carbs": 31,
    "protein": 12.5,
    "fat": 7.5,
    "fiber": 6.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-9",
    "name": "Rajma",
    "category": "Dal",
    "calories": 270,
    "carbonFootprint": 0.55,
    "carbs": 42,
    "protein": 14.0,
    "fat": 5.0,
    "fiber": 11.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-10",
    "name": "Chole",
    "category": "Dal",
    "calories": 280,
    "carbonFootprint": 0.58,
    "carbs": 44,
    "protein": 13.5,
    "fat": 6.0,
    "fiber": 10.5,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-11",
    "name": "Sambar",
    "category": "Dal",
    "calories": 180,
    "carbonFootprint": 0.36,
    "carbs": 28,
    "protein": 7.5,
    "fat": 4.0,
    "fiber": 6.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-12",
    "name": "Paneer Butter Masala",
    "category": "Paneer",
    "calories": 420,
    "carbonFootprint": 2.40,
    "carbs": 14,
    "protein": 16.0,
    "fat": 34.0,
    "fiber": 2.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-13",
    "name": "Shahi Paneer",
    "category": "Paneer",
    "calories": 430,
    "carbonFootprint": 2.50,
    "carbs": 16,
    "protein": 15.5,
    "fat": 35.5,
    "fiber": 1.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-14",
    "name": "Palak Paneer",
    "category": "Paneer",
    "calories": 350,
    "carbonFootprint": 2.10,
    "carbs": 12,
    "protein": 17.0,
    "fat": 26.0,
    "fiber": 4.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-15",
    "name": "Kadai Paneer",
    "category": "Paneer",
    "calories": 380,
    "carbonFootprint": 2.20,
    "carbs": 15,
    "protein": 16.5,
    "fat": 29.0,
    "fiber": 3.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-16",
    "name": "Aloo Gobi",
    "category": "Vegetable",
    "calories": 180,
    "carbonFootprint": 0.28,
    "carbs": 26,
    "protein": 4.5,
    "fat": 7.0,
    "fiber": 4.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-17",
    "name": "Bhindi Masala",
    "category": "Vegetable",
    "calories": 170,
    "carbonFootprint": 0.24,
    "carbs": 18,
    "protein": 3.8,
    "fat": 9.0,
    "fiber": 5.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-18",
    "name": "Baingan Bharta",
    "category": "Vegetable",
    "calories": 190,
    "carbonFootprint": 0.27,
    "carbs": 20,
    "protein": 3.2,
    "fat": 11.0,
    "fiber": 6.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-19",
    "name": "Mixed Vegetable Curry",
    "category": "Vegetable",
    "calories": 210,
    "carbonFootprint": 0.30,
    "carbs": 24,
    "protein": 5.0,
    "fat": 10.0,
    "fiber": 5.5,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-20",
    "name": "Aloo Matar",
    "category": "Vegetable",
    "calories": 220,
    "carbonFootprint": 0.34,
    "carbs": 32,
    "protein": 6.5,
    "fat": 7.5,
    "fiber": 5.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-21",
    "name": "Roti",
    "category": "Bread",
    "calories": 120,
    "carbonFootprint": 0.10,
    "carbs": 22,
    "protein": 3.8,
    "fat": 1.2,
    "fiber": 2.8,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-22",
    "name": "Butter Roti",
    "category": "Bread",
    "calories": 150,
    "carbonFootprint": 0.18,
    "carbs": 22,
    "protein": 3.8,
    "fat": 5.0,
    "fiber": 2.8,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-23",
    "name": "Naan",
    "category": "Bread",
    "calories": 260,
    "carbonFootprint": 0.28,
    "carbs": 45,
    "protein": 7.5,
    "fat": 5.0,
    "fiber": 2.0,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-24",
    "name": "Butter Naan",
    "category": "Bread",
    "calories": 320,
    "carbonFootprint": 0.40,
    "carbs": 45,
    "protein": 7.5,
    "fat": 12.0,
    "fiber": 2.0,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-25",
    "name": "Paratha",
    "category": "Bread",
    "calories": 300,
    "carbonFootprint": 0.35,
    "carbs": 42,
    "protein": 6.0,
    "fat": 12.5,
    "fiber": 3.2,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-26",
    "name": "Aloo Paratha",
    "category": "Bread",
    "calories": 340,
    "carbonFootprint": 0.42,
    "carbs": 52,
    "protein": 7.0,
    "fat": 12.0,
    "fiber": 4.5,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-27",
    "name": "Poori",
    "category": "Bread",
    "calories": 110,
    "carbonFootprint": 0.14,
    "carbs": 14,
    "protein": 2.2,
    "fat": 5.5,
    "fiber": 1.2,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-28",
    "name": "Idli",
    "category": "South Indian",
    "calories": 58,
    "carbonFootprint": 0.08,
    "carbs": 12,
    "protein": 1.8,
    "fat": 0.2,
    "fiber": 0.8,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-29",
    "name": "Plain Dosa",
    "category": "South Indian",
    "calories": 170,
    "carbonFootprint": 0.20,
    "carbs": 29,
    "protein": 3.8,
    "fat": 3.8,
    "fiber": 1.5,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-30",
    "name": "Masala Dosa",
    "category": "South Indian",
    "calories": 390,
    "carbonFootprint": 0.42,
    "carbs": 56,
    "protein": 7.5,
    "fat": 14.5,
    "fiber": 4.8,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-31",
    "name": "Uttapam",
    "category": "South Indian",
    "calories": 250,
    "carbonFootprint": 0.30,
    "carbs": 42,
    "protein": 5.5,
    "fat": 6.0,
    "fiber": 3.0,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-32",
    "name": "Vada",
    "category": "South Indian",
    "calories": 140,
    "carbonFootprint": 0.15,
    "carbs": 16,
    "protein": 4.2,
    "fat": 7.0,
    "fiber": 2.5,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-33",
    "name": "Upma",
    "category": "South Indian",
    "calories": 220,
    "carbonFootprint": 0.22,
    "carbs": 34,
    "protein": 5.0,
    "fat": 7.0,
    "fiber": 3.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-34",
    "name": "Poha",
    "category": "Breakfast",
    "calories": 250,
    "carbonFootprint": 0.20,
    "carbs": 42,
    "protein": 4.5,
    "fat": 7.2,
    "fiber": 2.6,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-35",
    "name": "Sabudana Khichdi",
    "category": "Breakfast",
    "calories": 330,
    "carbonFootprint": 0.38,
    "carbs": 58,
    "protein": 3.0,
    "fat": 10.0,
    "fiber": 1.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-36",
    "name": "Khichdi",
    "category": "Rice",
    "calories": 290,
    "carbonFootprint": 0.36,
    "carbs": 48,
    "protein": 8.5,
    "fat": 7.0,
    "fiber": 4.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-37",
    "name": "Chicken Curry",
    "category": "Non-Veg",
    "calories": 350,
    "carbonFootprint": 2.10,
    "carbs": 10,
    "protein": 28.0,
    "fat": 22.0,
    "fiber": 2.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-38",
    "name": "Butter Chicken",
    "category": "Non-Veg",
    "calories": 490,
    "carbonFootprint": 2.80,
    "carbs": 14,
    "protein": 30.0,
    "fat": 34.0,
    "fiber": 1.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-39",
    "name": "Fish Curry",
    "category": "Non-Veg",
    "calories": 320,
    "carbonFootprint": 1.40,
    "carbs": 8,
    "protein": 26.0,
    "fat": 20.0,
    "fiber": 1.5,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-40",
    "name": "Egg Curry",
    "category": "Non-Veg",
    "calories": 270,
    "carbonFootprint": 0.95,
    "carbs": 9,
    "protein": 15.0,
    "fat": 19.0,
    "fiber": 1.8,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-41",
    "name": "Boiled Egg",
    "category": "Non-Veg",
    "calories": 78,
    "carbonFootprint": 0.30,
    "carbs": 0.6,
    "protein": 6.3,
    "fat": 5.3,
    "fiber": 0.0,
    "unit": "kg CO2e per egg"
  },
  {
    "id": "food-42",
    "name": "Omelette",
    "category": "Non-Veg",
    "calories": 155,
    "carbonFootprint": 0.45,
    "carbs": 1.2,
    "protein": 11.0,
    "fat": 12.0,
    "fiber": 0.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-43",
    "name": "Curd",
    "category": "Dairy",
    "calories": 98,
    "carbonFootprint": 0.48,
    "carbs": 4.7,
    "protein": 3.5,
    "fat": 4.3,
    "fiber": 0.0,
    "unit": "kg CO2e per bowl"
  },
  {
    "id": "food-44",
    "name": "Lassi",
    "category": "Dairy",
    "calories": 180,
    "carbonFootprint": 0.72,
    "carbs": 24,
    "protein": 5.2,
    "fat": 6.5,
    "fiber": 0.0,
    "unit": "kg CO2e per glass"
  },
  {
    "id": "food-45",
    "name": "Gulab Jamun",
    "category": "Dessert",
    "calories": 150,
    "carbonFootprint": 0.32,
    "carbs": 22,
    "protein": 2.2,
    "fat": 6.0,
    "fiber": 0.2,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-46",
    "name": "Rasgulla",
    "category": "Dessert",
    "calories": 125,
    "carbonFootprint": 0.28,
    "carbs": 26,
    "protein": 2.8,
    "fat": 1.0,
    "fiber": 0.1,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-47",
    "name": "Kheer",
    "category": "Dessert",
    "calories": 220,
    "carbonFootprint": 0.75,
    "carbs": 32,
    "protein": 5.0,
    "fat": 8.0,
    "fiber": 0.4,
    "unit": "kg CO2e per bowl"
  },
  {
    "id": "food-48",
    "name": "Jalebi",
    "category": "Dessert",
    "calories": 180,
    "carbonFootprint": 0.22,
    "carbs": 36,
    "protein": 1.5,
    "fat": 3.5,
    "fiber": 0.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-49",
    "name": "Samosa",
    "category": "Snack",
    "calories": 262,
    "carbonFootprint": 0.30,
    "carbs": 32,
    "protein": 4.2,
    "fat": 13.0,
    "fiber": 2.8,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-50",
    "name": "Kachori",
    "category": "Snack",
    "calories": 290,
    "carbonFootprint": 0.34,
    "carbs": 34,
    "protein": 5.0,
    "fat": 15.0,
    "fiber": 3.0,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-51",
    "name": "Pav Bhaji",
    "category": "Street Food",
    "calories": 450,
    "carbonFootprint": 0.72,
    "carbs": 62,
    "protein": 9.5,
    "fat": 18.0,
    "fiber": 7.2,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-52",
    "name": "Vada Pav",
    "category": "Street Food",
    "calories": 290,
    "carbonFootprint": 0.36,
    "carbs": 42,
    "protein": 6.2,
    "fat": 11.0,
    "fiber": 3.8,
    "unit": "kg CO2e per piece"
  },
  {
    "id": "food-53",
    "name": "Pani Puri",
    "category": "Street Food",
    "calories": 180,
    "carbonFootprint": 0.18,
    "carbs": 28,
    "protein": 3.2,
    "fat": 6.5,
    "fiber": 2.0,
    "unit": "kg CO2e per serving"
  },
  {
    "id": "food-54",
    "name": "Bhel Puri",
    "category": "Street Food",
    "calories": 220,
    "carbonFootprint": 0.20,
    "carbs": 38,
    "protein": 4.8,
    "fat": 5.5,
    "fiber": 3.5,
    "unit": "kg CO2e per serving"
  }
];

// Eco Rating Helper based on carbon footprint (kg CO2e)
export function getEcoGrade(carbonFootprint) {
  if (carbonFootprint <= 0.25) return { grade: 'A', class: 'eco-grade-a', label: 'Very Eco' };
  if (carbonFootprint <= 0.50) return { grade: 'B', class: 'eco-grade-b', label: 'Low Eco' };
  if (carbonFootprint <= 1.20) return { grade: 'C', class: 'eco-grade-c', label: 'Moderate' };
  if (carbonFootprint <= 2.50) return { grade: 'D', class: 'eco-grade-d', label: 'High CO₂' };
  return { grade: 'E', class: 'eco-grade-e', label: 'Heavy CO₂' };
}
